# Generated by Django 5.1.7 on 2025-09-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
    ]
