# Generated by Django 5.1.7 on 2025-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner_alter_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
