# Generated by Django 5.1.7 on 2025-10-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
