# Generated by Django 5.1.7 on 2025-10-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_is_acitve_listing_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_active',
        ),
    ]
